version: 2

multi-ecosystem-groups:
  all-updates:
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "America/New_York"
    target-branch: "dev"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all-updates"
  - package-ecosystem: "npm"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all-updates"
    groups:
      ai-sdk:
        patterns:
          - "@ai-sdk/*"
          - "ai"
      next:
        patterns:
          - "next-*"
          - "next"
      react:
        patterns:
          - "babel-plugin-react-compiler"
          - "jotai"
          - "react-compiler-runtime"
          - "react-dom"
          - "react-error-boundary"
          - "react"
          - "use-local-storage-state"
          - "use-stick-to-bottom"
      dexie:
        patterns:
          - "dexie-react-hooks"
          - "dexie"
      radix:
        patterns:
          - "@radix-ui/*"
          - "@xyflow/react"
          - "embla-carousel-react"
          - "lucide-react"
          - "motion"
      ai-elements:
        patterns:
          - "@streamdown/code"
          - "ai-elements"
          - "remend"
          - "shiki"
          - "streamdown"
      types:
        patterns:
          - "@types/*"
      tailwindcss:
        patterns:
          - "@tailwindcss/*"
          - "class-variance-authority"
          - "clsx"
          - "tailwind-merge"
          - "tailwindcss"
          - "tw-animate-css"
      eslint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint-config-*"
          - "eslint-plugin-*"
          - "eslint"
      prettier:
        patterns:
          - "prettier-plugin-*"
          - "prettier"
      postcss:
        patterns:
          - "autoprefixer"
          - "cssnano"
          - "postcss-*"
          - "postcss"
      conventional-changelog:
        patterns:
          - "conventional-changelog*"
