name: DEV Build & Deploy

on:
  workflow_dispatch:

  push:
    branches:
      - "dev"
    paths:
      - "app/**.*"
      - "public/**.*"
      - "package.json"
      - "package-lock.json"
      - "next.config.json"
      - "tailwind.config.json"
      - "postcss.config.json"
      - "tsconfig.json"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APP_DISPLAY_NAME: ${{ vars.APP_DISPLAY_NAME }}
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
  AZURE_WEBAPP_PACKAGE_PATH: ${{ vars.AZURE_WEBAPP_PACKAGE_PATH || '.' }}
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}

jobs:
  build-and-deploy:
    environment:
      name: "dev"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    runs-on: ubuntu-latest
    steps:
      - name: 📤 Notify Teams
        uses: mikesprague/teams-incoming-webhook-action@a524ce1761a21193c9cd79daae855d140a912df5 # v2.1.0
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ env.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: ${{ env.APP_DISPLAY_NAME }} Deployment Started
          color: info

      - name: 👷 Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: 🏗️ Setup Node.js ${{ vars.NODE_VERSION }} environment
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ vars.NODE_VERSION }}
          check-latest: true

      - name: ⚡  Cache node_modules and .next folder
        id: cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: ⬆️ Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        shell: bash
        run: npm install --legacy-peer-deps

      - name: 🛠️ Build app
        shell: bash
        run: npm run build

      - name: 📦 Zip all files for deployment step
        # IMPORTANT: .next is a hidden folder and will NOT be included in the zip unless we specify it
        run: zip ${{ env.AZURE_WEBAPP_NAME}}.zip ./* .next -qr

      - name: 🚀 Deploy to Azure App Service
        id: deploy-to-webapp
        uses: azure/webapps-deploy@02a81bead70021f5284939794bcec79c271ab383 # v3.0.8
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/${{ env.AZURE_WEBAPP_NAME}}.zip
          type: zip

      - name: ⚠️ Cancelled Notification
        if: ${{ cancelled() }}
        uses: mikesprague/teams-incoming-webhook-action@a524ce1761a21193c9cd79daae855d140a912df5 # v2.1.0
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ env.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: ${{ env.APP_DISPLAY_NAME }} Deployment Cancelled
          color: warning

      - name: ⛔ Failure Notification
        if: ${{ failure() }}
        uses: mikesprague/teams-incoming-webhook-action@a524ce1761a21193c9cd79daae855d140a912df5 # v2.1.0
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ env.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: ${{ env.APP_DISPLAY_NAME }} Deployment Failed
          color: failure

      - name: 🎉 Success Notification
        if: ${{ success() }}
        uses: mikesprague/teams-incoming-webhook-action@a524ce1761a21193c9cd79daae855d140a912df5 # v2.1.0
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ env.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: ${{ env.APP_DISPLAY_NAME }} Deployment Successful
          color: success
